
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage,Toplevel


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window_RMS = Tk()

window_RMS.geometry("1024x600")
window_RMS.configure(bg = "#212E4D")


canvas = Canvas(
    window_RMS,
    bg = "#212E4D",
    height = 600,
    width = 1024,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    39.0,
    60.0,
    985.0,
    540.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    91.0,
    222.0,
    985.0,
    374.0,
    fill="#BECDDA",
    outline="")

canvas.create_text(
    39.0,
    24.0,
    anchor="nw",
    text="RMS",
    fill="#D9D9D9",
    font=("Inter Light", 30 * -1)
)

canvas.create_text(
    156.0,
    113.0,
    anchor="nw",
    text="IA",
    fill="#212E4D",
    font=("Inter Bold", 50 * -1)
)

canvas.create_text(
    156.0,
    270.0,
    anchor="nw",
    text="IA",
    fill="#212E4D",
    font=("Inter Bold", 50 * -1)
)

canvas.create_text(
    156.0,
    443.0,
    anchor="nw",
    text="IA",
    fill="#212E4D",
    font=("Inter Bold", 50 * -1)
)

canvas.create_text(
    600.0,
    113.0,
    anchor="nw",
    text="VA",
    fill="#212E4D",
    font=("Inter Bold", 50 * -1)
)

canvas.create_text(
    600.0,
    270.0,
    anchor="nw",
    text="VB",
    fill="#212E4D",
    font=("Inter Bold", 50 * -1)
)

canvas.create_text(
    600.0,
    443.0,
    anchor="nw",
    text="VC",
    fill="#212E4D",
    font=("Inter Bold", 50 * -1)
)

canvas.create_rectangle(
    594.0,
    -1.0,
    595.0,
    60.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    509.0,
    57.0,
    512.0,
    540.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    844.0,
    -1.0,
    845.0,
    60.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    0.0,
    60.0,
    91.0,
    540.0,
    fill="#E8CA2A",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=0.0,
    y=60.0,
    width=91.0,
    height=91.0
)

canvas.create_rectangle(
    235.0,
    107.0,
    444.0,
    174.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    704.0,
    107.0,
    913.0,
    174.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    235.0,
    443.0,
    444.0,
    510.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    700.0,
    443.0,
    909.0,
    510.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    241.0,
    264.0,
    450.0,
    331.0,
    fill="#BECDDA",
    outline="")

canvas.create_rectangle(
    704.0,
    265.0,
    913.0,
    332.0,
    fill="#BECDDA",
    outline="")
window_RMS.resizable(False, False)
window_RMS.mainloop()
